Export test results test addon
bitrise-steplib/bitrise-step-android-unit-test pull request #13
Opened 2019-04-30 15:27 UTC by lszucs

2019-05-03 13:12 UTC, trapacska commented
Please separate addon related logic to a separate package. Also you can keep android project based logic in a shared package but do not have it under the addon package.

2019-05-10 14:15 UTC, godrei commented on main.go
> +func artifactsToMap(artifacts []gradle.Artifact) map[string]string {
seems to be unused

2019-05-10 14:18 UTC, godrei commented on main.go
> +			if err := testaddon.ExportArtifact(artifact.Path, baseDir, uniqueDir); err != nil {
does it make sense to call this if an error occurred above?

2019-05-10 14:20 UTC, godrei commented on testaddon.go
> +	return parts[i-2], nil
just to be sure, pls validate the index before indexing the array

2019-05-10 14:20 UTC, godrei commented on testaddon.go
> +	variant := parts[i+1]
just to be sure, pls validate the index before indexing the array

2019-05-10 14:23 UTC, godrei commented on testaddon.go
> +func getModule(path string) (string, error) {
pls merge with `getVariant`

2019-05-10 14:25 UTC, godrei commented on testaddon/testaddon.go
> +		exportDir := strings.Join([]string{baseDir, uniqueDir}, "/")
pls use filepath.Join

2019-05-10 14:28 UTC, godrei requested changes
pls have a look at my notes

2019-05-10 14:56 UTC, godrei approved these changes

2019-05-10 14:59 UTC, merged